export const COMMON_DICT: Record<string, string[]> = {
  "ceo": ["генеральный директор", "гендиректор", "chief executive officer"],
  "cmo": ["директор по маркетингу", "маркетинг директор", "chief marketing officer"],
  "cfo": ["финансовый директор", "директор по финансам", "chief financial officer"],
  "coo": ["операционный директор", "chief operating officer"],
  "cpo": ["chief product officer", "директор по продукту"],
  "cto": ["технический директор", "chief technology officer"],
  "владелец продукта": ["product owner", "po"],
  "product owner": ["владелец продукта", "po"],
  "po": ["product owner", "владелец продукта"],
  "product manager": ["менеджер продукта", "продакт", "продакт-менеджер"],
  "менеджер продукта": ["product manager", "продакт", "продакт-менеджер"],
  "продакт": ["product manager", "менеджер продукта", "продакт-менеджер"],
  "project manager": ["руководитель проекта", "менеджер проекта", "проджект", "pm"],
  "руководитель проекта": ["project manager", "менеджер проекта", "проджект", "pm"],
  "менеджер проекта": ["project manager", "руководитель проекта", "проджект", "pm"],
  "проджект": ["project manager", "менеджер проекта", "руководитель проекта", "pm"],
  "pm": ["project manager", "менеджер проекта", "руководитель проекта", "проджект"],
  "tech lead": ["техлид", "технический лидер"],
  "техлид": ["tech lead", "технический лидер"],
  "frontend": ["фронтенд", "фронт", "react", "vue", "angular", "front-end"],
  "фронтенд": ["frontend", "front-end", "react", "vue", "angular", "фронт"],
  "backend": ["бэкенд", "бэк", "back-end", "python", "java", "golang", "php", "node", "c#"],
  "бэкенд": ["backend", "back-end", "python", "java", "golang", "php", "node", "c#", "бэк"],
  "qa": ["тестировщик", "tester", "тестирование", "test", "qaa", "qa engineer"],
  "тестировщик": ["qa", "tester", "тестирование", "test", "qa engineer"],
  "devops": ["девопс", "sre"],
  "девопс": ["devops", "sre"],
  "android": ["андроид", "mobile", "мобильный"],
  "ios": ["айос", "mobile", "мобильный", "swift", "apple"],
  "fullstack": ["фуллстек", "full-stack", "фулстек"],
  "дизайнер": ["designer", "ui/ux", "ui", "ux", "product designer", "продуктовый дизайнер"],
  "designer": ["дизайнер", "ui/ux", "ui", "ux", "product designer", "продуктовый дизайнер"],
  "аналитик": ["analyst", "data", "bi", "dwh", "system analyst", "системный аналитик"],
  "analyst": ["аналитик", "data", "bi", "dwh", "system analyst"],
  "hr": ["рекрутер", "персонал", "recruiter", "talent", "hrbp"],
  "рекрутер": ["hr", "персонал", "recruiter", "talent"]
};